### PR TITLE
Retry connection with user DB if master connection fails

### LINKED ISSUE #89: support for user authentication without access to master db
Hi gang,

I'm trying to use Azure/sql-action in the "deploy" phase of my workflow when deploying an ASP.NET Core app to Azure.

My Azure SQL server definitely has "Allow Azure services and resources to access this server" set to "Yes", but when my workflow runs I get the following error:

Error: Failed to add firewall rule. Unable to detect client IP Address. Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user '(redacted)'..

My code looks like this:

   - name: Apply EF migration script
        uses: Azure/sql-action@v1
        with:
          server-name: (my server name).database.windows.net
          connection-string: ${{ secrets.CONNECTIONSTRING_PUCKA }}
          sql-file: ./migrate.sql

In the server-name attribute I've tried it with and without the "tcp:" prefix (which is in the connection string) but I get the same error both ways.

Your README says if I have "allow azure services" set to "yes" then I should be fine. Am I doing something wrong?

### PR DESCRIPTION
**Pull request by zijchen**
Fixes #89

### CODE REVIEW

File: src/SqlUtils.ts [hunk 1]
```diff
@@ -5,52 +5,96 @@ import Constants from "./Constants";
 import SqlConnectionConfig from "./SqlConnectionConfig";
 
 export default class SqlUtils {
+
+    /**
+     * Tries connection to server to determine if client IP address is restricted by the firewall.
+     * First tries with master connection, and then with user DB if first one fails.
+     * Returns the client IP address if firewall restriction is present, or an empty string if connection succeeds. Throws otherwise.
```
Comment (kisantia) [inline src/SqlUtils.ts:12]: nit: use @returns for doc comment and add @param comment for connectionConfig

File: src/SqlUtils.ts [hunk 2]
```diff
@@ -5,52 +5,96 @@ import Constants from "./Constants";
...
+        }
+    }
+
+    /**
+     * Tries connection with the specified configuration.
+     * @param config Configuration for the connection.
+     * @param useMaster If true, uses "master" instead of the database specified in @param config. Every other config remains the same.
+     * @param suppressError If true, will not throw connection errors. Non-connection errors will always be thrown.
+     * @returns If connection succeeds, returns empty string. If connection fails due to firewall rule, returns the client's IP address.
+     * Otherwise returns undefined if there were errors but were suppressed by @param suppressError.
```
Comment (kisantia) [inline src/SqlUtils.ts:37]: it's a little confusing that the return type has 3 different states that the caller needs to know: ipAddress = connection failed due to firewall rule, empty string = successfully connected, and undefined = error when connecting.

Can this return an object that has properties that make it more clear what happened? Maybe something like
```
{
    success: boolean,
    ipAddress?: string
}
```

File: src/SqlUtils.ts (hunk 1 above)
Comment (zijchen) [reply src/SqlUtils.ts]: Fixed

File: src/SqlUtils.ts (hunk 2 above)
Comment (zijchen) [reply src/SqlUtils.ts]: Added a ConnectionResult interface

File: src/SqlUtils.ts [hunk 3]
```diff
@@ -4,39 +4,54 @@ import * as mssql from "mssql";
 import Constants from "./Constants";
 import SqlConnectionConfig from "./SqlConnectionConfig";
 
+export interface ConnectionResult {
+    success: boolean,                   // True if connection succeeds, false otherwise
```
Comment (kisantia) [inline src/SqlUtils.ts:8]: use js doc comments so that they show up when hovering over these properties when they're used in other places in the code

File: src/SqlUtils.ts [hunk 4]
```diff
@@ -4,39 +4,54 @@ import * as mssql from "mssql";
...
         // First try connection to master
-        let ipAddress = await this.tryConnection(connectionConfig, true, true);
-        if (ipAddress !== undefined) {
-            return ipAddress;
+        let result = await this.tryConnection(connectionConfig, true);
+        if (result.success) {
+            result.connection?.close();
+            return '';
+        }
+        else if (result.ipAddress !== undefined) {
```
Comment (kisantia) [inline src/SqlUtils.ts:29]: this can be simplified to `else if (result.ipAddress)` if we don't have to worry about `result.ipAddress` being an empty string and still returning it when it is

File: src/SqlUtils.ts [hunk 5]
```diff
@@ -46,22 +61,18 @@ export default class SqlUtils {
         try {
             core.debug(`Validating if client has access to '${connectionConfig.database}' on '${connectionConfig.server}'.`);
             const pool = await mssql.connect(connectionConfig);
-            pool.close();
-            return '';                  // Connection successful
+            return {
+                success: true,
+                connection: pool
+            } as ConnectionResult;
```
Comment (kisantia) [inline src/SqlUtils.ts:67]: is the `as ConnectionResult` necessary?

File: src/SqlUtils.ts (hunk 3 above)
Comment (zijchen) [reply src/SqlUtils.ts]: Updated

File: src/SqlUtils.ts (hunk 5 above)
Comment (zijchen) [reply src/SqlUtils.ts]: Nope. Updated

File: src/SqlUtils.ts (hunk 4 above)
Comment (zijchen) [reply src/SqlUtils.ts]: Updated

**Review by kisantia — APPROVED** [review]

**Comment by zijchen** [comment]
@mabster could you give this a try to see if it addresses your issue?

You can use the action directly from this PR branch by changing your yaml to 
```yaml
- uses: azure/sql-action@zijchen/issue89
```

**Comment by zijchen** [comment]
@mabster Yes the inputs are the same as of the latest commit.

**Comment by mabster** [comment]
OK, this is odd. 

I generate my migrate.sql script using dotnet ef migrations script, and then run it using your new version, and I just get a series of errors as my output:

```
Error: Incorrect syntax near '﻿'.
Error: Incorrect syntax near 'GO'.
Error: Incorrect syntax near 'GO'.
Error: Incorrect syntax near 'GO'.
Error: Incorrect syntax near 'GO'.
Error: Incorrect syntax near 'GO'.
Error: Incorrect syntax near 'GO'.
... lots more of the same ...
Error: Failed to execute query.
```

Is there a "verbose" input I can pass to get more detail on the error? 

The script is pretty straight forward. Here's the first few statements from one I generated locally:

```
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
GO

IF NOT EXISTS(SELECT * FROM [__EFMigrationsHistory] WHERE [MigrationId] = N'20220330033849_InitialCreate')
BEGIN
    CREATE TABLE [Courses] (
        [Id] int NOT NULL IDENTITY,
        [Code] nvarchar(max) NOT NULL,
        [Name] nvarchar(max) NOT NULL,
        [IsEnabled] bit NOT NULL,
        CONSTRAINT [PK_Courses] PRIMARY KEY ([Id])
    );
END;
GO
```

**Comment by mabster** [comment]
The file generated by `dotnet ef migrations script` is "UTF-8 with BOM" encoded. Could that be an issue? Is that 100% compatible with plain-old "UTF-8"?

https://github.com/Azure/sql-action/blob/de9671df5b9f013b1f73774633f07eb1fce1538c/src/AzureSqlAction.ts#L95

**Comment by zijchen** [comment]
@mabster This could be because this branch is based off the v2 branch, which uses [node-mssql](https://github.com/tediousjs/node-mssql) instead of sqlcmd. `GO` is more of a sqlcmd statement than a native T-SQL statement. Could you remove the `GO` statements in your script and try again?

**Comment by zijchen** [comment]
I can see this being an issue for folks migrating to v2, created #107 for it.

**Comment by mabster** [comment]
Oh snap I got it to work.

Added this step between "generate the script" and "apply the script":

```
 - name: Remove 'GO' from migration script
        run: (Get-Content ${{env.DOTNET_ROOT}}/migrate.sql | ? { $_ -ne 'GO' }) | Set-Content ${{env.DOTNET_ROOT}}/migrate.sql
```

It's a bit of a hack but the script ran fine once the "GO" lines were removed.

**Comment by zijchen** [comment]
Thanks for the confirmation. I'll merge this PR now, but we are considering integrating [go-sqlcmd](https://github.com/microsoft/go-sqlcmd) for the script action, which would restore some of the sqlcmd functionality.
