### PR TITLE
sqlpackage path argument, dotnet tool sqlpackage

### LINKED ISSUE #180: SSDT error while deploying it from GitHub self hosted runner
Hi all,

I am getting the below error when publishing dacpac from self hosted runner.

`Error: There was an error when attempting to execute the process 'sqlpackage'. This may indicate the process failed to start. Error: spawn sqlpackage ENOENT`

It would be good to get some assistance on this issue.

### LINKED ISSUE #211: Support SqlPackage.exe at a specific path
Currently the action searches for the Windows executable by looking in three common installation locations and then failing if not found.  However, there are other methods available to install it locally (dotnet tools in my case).  I propose an additional configuration option to specify the location of sqlpackage.exe or to search for it via the path environment variable.  We have self-hosted runners that we try to keep as clean as possible as this reduces the need for software to maintain software on the server.

### PR DESCRIPTION
**Pull request by dzsquared**
3 changes lumped together in this PR (I let it get away from me):

1. for dacpac and sqlproj action there's an optional action parameter `sqlpackage-path` which overrides any sqlpackage location detection by the action except to check that it exists. (fixes #211)
2. dotnet tool location for a global install of sqlpackage is checked
3. the full semantic version is parsed for version comparison, instead of just 150 vs 160, which was leading to the wrong version being picked (162.1 vs 162.2 would default to one based on who installed instead of the actual version)

also fixes #180 

future PR needed to remove SSMS-related logic as it hasn't installed sqlpackage.exe for quite some time

### CODE REVIEW

File: src/AzureSqlActionHelper.ts [hunk 1]
```diff
@@ -4,14 +4,23 @@ import * as path from "path";
...
 const IS_WINDOWS = process.platform === 'win32';
 const IS_LINUX = process.platform === 'linux';
 
 export default class AzureSqlActionHelper {
     
-    public static async getSqlPackagePath(): Promise<string> {
+    public static async getSqlPackagePath(inputs: IDacpacActionInputs): Promise<string> {
+        if (inputs.sqlpackagePath) {
+            if (!fs.existsSync(inputs.sqlpackagePath)) {
+                throw new Error(`SqlPackage.exe not found at provided path: ${inputs.sqlpackagePath}`);
```
Comment (zijchen) [inline src/AzureSqlActionHelper.ts:18]: sqlpackage without "exe" to be OS-agnostic

File: src/AzureSqlActionHelper.ts [hunk 2]
```diff
@@ -125,6 +134,9 @@ export default class AzureSqlActionHelper {
     private static async _getSqlPackageExecutablePath(): Promise<string> {
         core.debug('Getting location of SQLPackage.exe');
 
+        let sqlPackagePathInstalledWithDotnetTool = await this._getSqlPackageInstalledDotnetTool()
```
Comment (zijchen) [inline src/AzureSqlActionHelper.ts:137]: missing semicolon

File: src/AzureSqlActionHelper.ts [hunk 3]
```diff
@@ -146,16 +164,45 @@ export default class AzureSqlActionHelper {
...
+    private static async _getSqlPackageExecutableVersion(sqlPackagePath: string): Promise<semver.SemVer> {
+        let versionOutput = '';
+        await exec.exec(`"${sqlPackagePath}"`, ['/version'], {
+            listeners: {
+                stdout: (data: Buffer) => versionOutput += data.toString()
+            }
+        });
+
+        let version = versionOutput.trim();
+        if (!semver.valid(version)) {
```
Comment (zijchen) [inline src/AzureSqlActionHelper.ts:186]: Please test if semver handles suffixes like "-preview"

**Review by zijchen — DISMISSED** [review]

File: src/AzureSqlActionHelper.ts [hunk 4]
```diff
@@ -116,28 +125,39 @@ export default class AzureSqlActionHelper {
     }
 
     /**
-     * SqlPackage.exe can be installed in two ways:
-     *  1. SQL Server Management Studio (SSMS) and the Dac Framework MSI installs it in location C:/Program Files/Microsoft SQL Server/{SqlVersopn}/DAC/bin/SqlPackage.exe'
-     *  2. SSDT (SQL Server Data Tools) installs it in location VS Install Directory/Common7/IDE/Extensions/Microsoft/SQLDB/DAC/{SqlVersion}
+     * SqlPackage.exe can be installed in four ways:
+     *  0. as a global dotnet tool
+     *  1. SQL Server Management Studio (SSMS) used to install it to in location C:/Program Files/Microsoft SQL Server/{SqlVersopn}/DAC/bin/SqlPackage.exe' (REMOVE in the future)
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:130]: How was this order determined? dotnet tool as `0` makes a ton of sense to me. Curious why SSMS is next on the pecking order.

File: src/AzureSqlActionHelper.ts [hunk 5]
```diff
@@ -116,28 +125,39 @@ export default class AzureSqlActionHelper {
...
 
         let sqlPackagePathInstalledWithSSMS = await this._getSqlPackageInstalledWithSSMS();
-        core.debug(sqlPackagePathInstalledWithSSMS.toString());
+        core.debug(`SqlPackage (installed with SSMS) found at location: ${sqlPackagePathInstalledWithSSMS[0]}, version ${sqlPackagePathInstalledWithSSMS[1]}`);
 
         let sqlPackagePathInstalledWithDacMsi = await this._getSqlPackageInstalledWithDacMsi();
-        core.debug(sqlPackagePathInstalledWithDacMsi.toString());
+        core.debug(`SqlPackage (installed with DacFramework) found at location: ${sqlPackagePathInstalledWithDacMsi[0]}, version ${sqlPackagePathInstalledWithDacMsi[1]}`);
 
         let sqlPackagePatInstalledWithSSDT = await this._getSqlPackageInstalledWithSSDT();
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:148]: While we're here, `sqlPackagePathInstalledWithSSDT`

File: src/AzureSqlActionHelper.ts [hunk 6]
```diff
@@ -116,28 +125,39 @@ export default class AzureSqlActionHelper {
...
+        core.debug(`SqlPackage (installed with SSDT) found at location: ${sqlPackagePatInstalledWithSSDT[0]}, version ${sqlPackagePatInstalledWithSSDT[1]}`);
+
 
+        // sort the versions in descending order and return the first path
+        let sqlPackageVersions = [sqlPackagePathInstalledWithDotnetTool[1], sqlPackagePathInstalledWithSSMS[1], sqlPackagePathInstalledWithDacMsi[1], sqlPackagePatInstalledWithSSDT[1]];
+        semver.rsort(sqlPackageVersions);
+        let maximumVersion = sqlPackageVersions[0];
         let sqlPackagePath = '';
-        if (maximumVersion === sqlPackagePathInstalledWithSSMS[1]) {
+        if (maximumVersion === sqlPackagePathInstalledWithDotnetTool[1]) {
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:157]: This should really be a `for` or `foreach` loop at this point to match a version with a path.

File: src/AzureSqlActionHelper.ts [hunk 7]
```diff
@@ -146,16 +166,50 @@ export default class AzureSqlActionHelper {
         else if (maximumVersion === sqlPackagePatInstalledWithSSDT[1]) {
             sqlPackagePath = sqlPackagePatInstalledWithSSDT[0];
         }
+        
 
-        if (!sqlPackagePath) {
-            throw new Error('Unable to find the location of SqlPackage.exe');
+        if (sqlPackagePath == '') {
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:171]: I think this will work anyway, but to prevent future regressions, may want to do `===` if this logic changes in the future

File: src/AzureSqlActionHelper.ts [hunk 8]
```diff
@@ -146,16 +166,50 @@ export default class AzureSqlActionHelper {
...
+        }
+
+        return version;
+    }
+
+    private static async _getSqlPackageExeInstalledDotnetTool(): Promise<[string, semver.SemVer]> {
+        let globalDotnetToolsPath = path.join(process.env['USERPROFILE'] as string, '.dotnet', 'tools');
+        let sqlPackagePath = path.join(globalDotnetToolsPath, 'SqlPackage.exe');
+        if (fs.existsSync(sqlPackagePath)) {
+            core.debug(`SqlPackage (installed with dotnet tool) found at location: ${sqlPackagePath}`);
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:204]: Are there going to be double debug statements (due to debug statements also existing in _getSqlPackageExecutablePath)

File: src/AzureSqlActionHelper.ts [hunk 9]
```diff
@@ -213,12 +267,13 @@ export default class AzureSqlActionHelper {
                 let sqlPackagaePath = path.join(dacDir, 'SqlPackage.exe');
                 if (fs.existsSync(sqlPackagaePath)) {
                     core.debug(`Dac Framework installed with Visual Studio found at ${sqlPackagaePath}`);
-                    return [sqlPackagaePath, parseInt(path.basename(dacDir))]
+                    let sqlpackageVersion = await this._getSqlPackageExecutableVersion(sqlPackagaePath);
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:270]: nit: camelCase

File: src/AzureSqlActionHelper.ts [hunk 10]
```diff
@@ -261,25 +316,24 @@ export default class AzureSqlActionHelper {
             if (!!installDir) {
                 let sqlPackagePath = path.join(installDir, 'SqlPackage.exe');
                 if (fs.existsSync(sqlPackagePath)) {
-                    core.debug(`SQLPackage.exe (installed with DacFramework) found at location: ${sqlPackagePath}`);
-                    return [sqlPackagePath, parseInt(registryKey.key.split("\\").slice(-1)[0])];
+                    core.debug(`SqlPackage (installed with DacFramework) found at location: ${sqlPackagePath}`);
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:319]: same question here re: debug statements duplicated

File: src/AzureSqlActionHelper.ts [hunk 11]
```diff
@@ -291,13 +345,14 @@ export default class AzureSqlActionHelper {
             if (!!versionSpecificRootDir) {
                 let sqlPackagePath = path.join(versionSpecificRootDir, 'Dac', 'bin', 'SqlPackage.exe');
                 if (fs.existsSync(sqlPackagePath)) {
-                    core.debug(`SqlPackage.exe (installed with SSMS) found at location: ${sqlPackagePath}`);
-                    return [sqlPackagePath, parseInt(registryKey.key.split("\\").slice(-1)[0])];
+                    core.debug(`SqlPackage (installed with SSMS) found at location: ${sqlPackagePath}`);
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:348]: and here

File: src/AzureSqlActionHelper.ts [hunk 12]
```diff
@@ -323,6 +378,12 @@ export default class AzureSqlActionHelper {
     }
 
     private static _getSqlPackageBinaryPathLinux(): string {
+        // check in dotnet tool default global path ~/.dotnet/tools
+        if (fs.existsSync('~/.dotnet/tools/sqlpackage')) {
```
Comment (chlafreniere) [inline src/AzureSqlActionHelper.ts:382]: this should be a const instead of repeating it

File: src/AzureSqlActionHelper.ts (hunk 4 above)
Comment (dzsquared) [reply src/AzureSqlActionHelper.ts:130]: I'm not sure, to be honest - this was existing code and is consistent with the ADO task.
I checked current SSMS installs and it doesn't bring SqlPackage.exe, so this shouldn't ever get picked up.  I left a note to remove this in the future (that should be a work item but I'm lazy)

File: src/AzureSqlActionHelper.ts (hunk 8 above)
Comment (dzsquared) [reply src/AzureSqlActionHelper.ts]: yep, that would have been too noisy - thanks - cleaned up and moved all positive case debug messages to the specific functions

File: src/AzureSqlActionHelper.ts (hunk 6 above)
Comment (dzsquared) [reply src/AzureSqlActionHelper.ts]: ripped out at part of moving to an interface

**Review by chlafreniere — APPROVED** [review]
Looks great, thanks so much for being receptive to comments/suggestions 😄!

**Review by zijchen — APPROVED** [review]
