### PR TITLE
Escape double quotes in connection string

### LINKED ISSUE #222: Can't use quotes in the connection string
My action config looks like this:

```yml
- uses: azure/sql-action@v2.2.1
  with:
    connection-string: '...;Authentication="Active Directory Default";'
    path: path/to/file.dacpac
    action: Publish
```

I got the error message: 

```
*** Unrecognized command line argument 'Directory'.
*** Unrecognized command line argument 'Default;'.
Error: The process 'C:\Program Files\Microsoft SQL Server\160\Dac\bin\SqlPackage.exe' failed with exit code 1
```

It looks as though the code to invoke `SqlPackage` isn't correctly handling quotes in the connection string:

```
"C:\Program Files\Microsoft SQL Server\160\Dac\bin\SqlPackage.exe" /Action:Publish "/TargetConnectionString:...;Authentication=Active" Directory Default; /SourceFile:path/to/file.dacpac
```

\- note the closing quote after `Active`.

I worked around this by removing the quotes from the connection string (ie `Authentication=Active Directory Default;`) and that appears to work, but the action ought to be able to handle the quotes.

### PR DESCRIPTION
**Pull request by zijchen**
Escape double quotes in connection string when passing to sqlpackage. Fixes #222 and #137

### CODE REVIEW

**Review by llali — DISMISSED** [review]

**Review by dzsquared — DISMISSED** [review]

File: src/SqlConnectionConfig.ts [hunk 1]
```diff
@@ -56,6 +52,31 @@ export default class SqlConnectionConfig {
         return auth?.replace(/\s/g, '').toLowerCase();
     }
 
+    /**
+     * Returns the connection string escaped by double quotes.
+     */
+    public get EscapedConnectionString() : string {
```
Comment (chlafreniere) [inline src/SqlConnectionConfig.ts:58]: Can we do effectively the same thing with `_parsedConnectionString` and iterate through keys/values so that we don't need to parse a second time?

Comment (zijchen) [reply src/SqlConnectionConfig.ts:58]: I did think about that but the issue with the key/value pair is the keys may have changed (e.g. Server becomes 'data source') and we'd still need to escape each value again. Since the full connection string is only used by sqlpackage, I wanted it to be as close to the one user supplied without changing it too much.

Comment (chlafreniere) [reply src/SqlConnectionConfig.ts:58]: Ahh, I see. Ok, I can live with that for sure. Can you put a comment here describing this decision?

Comment (zijchen) [reply src/SqlConnectionConfig.ts:58]: Added a comment

**Review by chlafreniere — APPROVED** [review]
