### PR TITLE
v2 - Remove client-id and tenant-id as inputs

### LINKED ISSUE #119: v2 - tenant-id and client-id are not optional
When not provided, it throws this error:
image

Note: Using AAD Service Principal Auth

### PR DESCRIPTION
**Pull request by zijchen**
Fixes #119 

Initial implementation of v2 used the tedious driver to test connection to database. For some reason their driver requires tenant-id and client-id to be explicitly set. However with go-sqlcmd implementation, this is no longer necessary.

### CODE REVIEW

**Comment by Benjin** [comment]
Why the change from tedious to go-sqlcmd?

File: src/SqlUtils.ts [hunk 1]
```diff
@@ -60,73 +54,105 @@ export default class SqlUtils {
...
             connectionConfig.database = "master";
         }
-
+        
+        let sqlCmdError = '';
         try {
             core.debug(`Validating if client has access to '${connectionConfig.database}' on '${connectionConfig.server}'.`);
-            const pool = await mssql.connect(connectionConfig);
+            let sqlCmdCall = this.buildSqlCmdCallWithConnectionInfo(connectionConfig);
+            sqlCmdCall += ` -Q "select getdate()"`;
```
Comment (Benjin) [inline src/SqlUtils.ts:66]: I wonder if a user might see this and get confused/concerned.  Maybe `SELECT 'Validating connection from GitHub SQL Action'`?

**Review by Benjin — APPROVED** [review]

**Comment by dzsquared** [comment]
> Why the change from tedious to go-sqlcmd?
> 
> Also, what situations were ClientId/TenantId required for? Were they supported before, and we're just making it explicit, or are they supported in some other way?

The current implementation (v1) utilizes sqlcmd, and through that it supports substituting sqlcmd variables into the scripts.  While changing to tedious simplified the support for various AAD auth types with script execution, it broke the variable substitution capabilities of sqlcmd.  Go-sqlcmd combines support for AAD auth types and sqlcmd variables

**Review by kisantia — APPROVED** [review]
